name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: checkboxes
  id: docs-read
  attributes:
    label: I have read the documentation
    options:
      - label: I have read the [documentation](https://github.com/tomer-w/victron-mqtt) and understand the setup process.
        required: true
- type: textarea
  id: bug-description
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  id: reproduction-steps
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: Please provide details about your environment.
    placeholder: |
      - Home Assistant version:
      - Home Assistant hardware:
      - Venus OS hardware (Cerbo GX, Raspberry Pi, etc.):
      - Integration version:
  validations:
    required: false
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
