name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for suggesting a new feature!
- type: checkboxes
  id: docs-read
  attributes:
    label: I have read the documentation and contribution instructions
    options:
      - label: I have read the [documentation](https://github.com/tomer-w/victron_mqtt?tab=contributing-ov-file#finding-mqtt-topics-with-mqtt-explorer).
        required: true
      - label: I tried to use mqtt-explorer as described in the docs to extract the topics I care about.
        required: true
- type: textarea
  id: feature-description
  attributes:
    label: Describe the feature
    description: A clear and concise description of the feature you'd like to see.
    placeholder: Tell us what you want!
  validations:
    required: true
- type: textarea
  id: mqtt-topics
  attributes:
    label: Required MQTT topics
    description: Please provide the MQTT topics required for this feature. Remove the installation ID from the topic strings (it is confidential). For each topic, include its meaning and units, and paste an example payload or value you observed in mqtt-explorer.
    placeholder: |
      Provide each topic using the format below:

      Example format and entries:

      - topic: N/{installation_id}/battery/{device_id}/Dc/0/Voltage
        meaning: Battery voltage
        units: V
        example_value: {"value":13.460000038146973}

      - topic: N/{installation_id}/battery/{device_id}/Dc/0/Current
        meaning: Battery current (positive = charging, negative = discharging)
        units: A
        example_value: {"value":5.12345}

      - topic: N/{installation_id}/tank/{device_id}/Remaining
        meaning: Remaining capacity of the tank
        units: %
        example_value: {"value":75}

      If you have many topics, list them one per bullet using the same fields above (topic, meaning, units, example_value).
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
